workflows:
  build-app:
    name: Build App
    instance_type: mac_pro
    max_build_duration: 60
    environment:
      vars:
        PROJECT_DIR: ios-test2
      groups:
        - Apple API key (Admin)
      xcode: 13.0
      cocoapods: default
    scripts:
      - keychain initialize
      - app-store-connect fetch-signing-files "io.codemagic.banaan" --type IOS_APP_STORE --create
      - keychain add-certificates
      - xcode-project use-profiles
      - xcode-project build-ipa --project "$PROJECT_DIR/banaan.xcodeproj" --scheme "banaan"
  test-app:
    name: Test App
    instance_type: mac_pro
    max_build_duration: 10
    environment:
      xcode: 12.5
      cocoapods: default
    scripts:
      - name: Run tests
        script: xcode-project run-tests --project "ios-test2/banaan.xcodeproj" --scheme "banaan" --device "iOS 14.0 iPhone 11"
        test_report: build/ios/test/*.xml
    artifacts:
      - /tmp/xcodebuild_logs/*.log
