definitions:
  inputs:
    xcode: &xcode-input
      description: Xcode version
      type: choice
      default: latest
      options:
        - 15.0
        - 15.1
        - 15.2
        - 15.3
        - 15.4
        - 16.0
        - 16.1
        - 16.2
        - 16.3
        - 16.4
        - 26.0
        - 26.1
        - latest

workflows:
  build-and-upload:
    name: Upload ipa
    inputs:
      xcode: *xcode-input
    environment:
      groups:
        - Apple API key (Admin)
      vars:
        APP_STORE_CONNECT_ALTOOL_VERBOSE_LOGGING: true
      xcode: "${{ inputs.xcode }}"
    scripts:
      - ls -l "*.ipa"
    artifacts:
      - "*.ipa"
    publishing:
      app_store_connect:
        submit_to_testflight: false
        submit_to_app_store: false
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
