definitions:
  inputs:
    xcode: &xcode-input
      description: Xcode version
      type: choice
      default: latest
      options:
        - latest
        - 26.1
        - 26.0
        - 16.4
        - 16.3
        - 16.2
        - 16.1
        - 16.0
workflows:
  build-app:
    inputs:
      xcode: *xcode-input
    name: Build app
    labels:
      - "${{ inputs.xcode }}"
    environment:
      xcode: "${{ inputs.xcode }}"
      groups:
        - Apple API key (Admin)
      vars:
        XCODE_VERSION: ${{ inputs.xcode }}
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmZUbFhQU0JaTnhrRXR3QkJWSXVSdXFvV1I4TTFZeXdwaEFJNjhDdkVSakNwRWJHT09UeUpITUlpdFpFVHFWU29XaG9iT3poeGU2NmI4WElPVGIyVjFycWZ4cWMweXRoelZybFVyQlhNN05yOWlOT0JOTkpxZGRaM25QLWtWbnRtYlAzQ2IxSEVrQnFteVNtMHBTUl9FV0g5dFY2M01nYVJ1TXU5ajM2S0lBTEpqck1fWG9QNVRHalRULWxxOFVsV1ItR1RzbTdWMGt3UVNKMXBoT05rakRMWkMwSW5KR2ZNS3liOGxJQXVwU0luUV85UElwczhfM3N5ZE5BYXJQSnRWb0lhaUtfV1NtU2U0SWZoNlZDTE0yWEhUQWh0S0RlM3QtdGhnd2ozX09WRUxIYW0tS2dLeFE0bDJEZTJNSExubU5vb1MxUFRLUXlNb0tnNzQyNXk4TzIydENqUFJpMFB3a2dCYkFFaVlIa2ZDdHo2Y0M5QXJwYTFkSXctLVRSWVJaM1hnbVpVRTFSLTVJN3U1eXE4cWNtNFBlSkpoTlNvTk96dF9aZTFFWWt0TmZvUURDTURneDFWWDVxcmVjY3oyR1NIY2UwcWhBTVR5QnNkQTJNVXZ3Q25qNDJidXM4T2dfbFZnRjVLQTYxSW9CRm9DS1BTbGNfdzJyWHJYMFNBcEFsbmdkdUFqbWtCTFVGZzVPQjRkMlJrS0JfN0pVM3RlVmlDTU1CaTM3VS1hQ1ppVUNpZEdxZmF5SE9EbEo3bWRNVFBONzJzbDRBYzR1U0o2dWlfQjl2Zm5KNmgyOVJ1N25IV19GSC1ub0dwTEVzZml6U3JGNVY1N3MyTGZMZ2pzWW9vbzRsRGUwX3dXWkZsM1JlODlXR3l6c0FZV05pcTl2S1NCRzlYMVg1NnpxLW8xbm5Kenh1a0w4NmoyY3o1MllXaUVKT0UzV2xOVEZLUEc2QkI0aENIZnY3UFRoRGV1bU5NM0k0TFVsMVVoQzdMeUVENjdfRmc4cGJaam5heEJwUkNzdGRWY012UGNPTm5DQm9FZ3VkX0VNc3puWVh5Y1BTajRfeUkwLTRTRWVjaGg3eDI2SWxhNVRUekNMRk1HQmk2RW5WY2hEVFZ0ZGZDNXljUEZSb3NQYUpObG54dHc1RXhNTzh3bEl3UkZYWkNoT0hTa2RWeEdEWnFQTWV0dk5OX2lhTFZaSTJ3MjMxR1A2WDlMeDMyTXZBZ0hoSkgzaUVjbDVXeEhrcE9QMm4tZm9hTzI1YTJjN29Bb21iNWlKamVjQ3JPeFBGTlJQajNQWk83aXdsZ3VCY2hTZDRzenA0azQ0UFlmRkhlb0tSU013cFMyZE1OLTdpWm1qU2s3eUFEVnVTTWJoaFBTSVpkc2FhTHpIclpidUtVOWExZE9adXZVSnRtemN2RnJJS1VMU2F5NVA0Z205U3FteGFmSHdRWTBiV25XamllZTY4RHctVjVhQ2stZ1B1aEo4V1FVTDZnTk90N3RjM1kwWHJrbEhWTWFfeURrNEhiXzZNQnhQTTZhMm5ZWng2WFEzVzNvRUlReVllYkU0MWdyMTNkam10LXREVmg0aXJsNnF1UjlfUkhNOF9vY2MzRzBEQ3F5RFdlU1Vua1VNTDh4VmRXWmdUdDAwTlhBYWVycXhQdXpEWk5fV29QX0kyOFV2dnpoRm0zM1BuZEJQMlRtZVhWX3d1VHJqVzlia1FFRS1ONjF0MlZaRDN5T0haX3JNVzZIckptNzlsUjRkVjZjRFhxTzRFRnBHcWxlNkN1cUJJcC0tMVNwVnpESWVkbmU2c3RQUWpqR2Y1V01YRVBGNW1zb2VZOVc5YUpEbU1UQ0x6dmFVUVNzNlBnTjhQekFPM2JLQ29aeGRuLWRzNUp0YmRUbjdiYVRSRERfWEpnaVkxM1FILXhlN3l3UnFiSjVOaFNoajcyaGNOdER5OWtwaXk0Q184YXZBbWphQmNpeFFsZ0tiYklUVGRDMWViT0dDQXE2RDhtZ1RCMTZZcUdKNDN3Mmt6U3p3TFlzRVJ4cFh4Y1poTFRmTTU3YjNCczQyOVFXc0FUa0N1bUo1VE9XSEh0ZEw5UUVTZUN2T0Y2YktIM3NuRDRPN3d1SnVPZkJlYUg3UFZrU1haM1hZeVdfU0Y5b2tmOUhOZzN2bWlCMWNoTXJkQTFZMGg5b2laNV9Ca01EV2pLRUhpc2tHSWNYa0lnbHBfb0xMM2N1azl2bmI2NlBXeVUzLW53SEhvWnFyOG1pd3lmSzU2cXh5aDF2YVNIZTFNNjhZeDRIT1Q2VDJVem5uS0lJOUd4MEVRUnFOTnNlM2NjR3lXMWZoVXBjZWtLU0owdWMyOWZ2Mm5wUzlBVWRrSUIydUhBMVdUWVBxcTdrSDVxWHhLRFFudmswb3BlZS01S3pqRm1BUmtlX0JjTjdNVzJxNGJVV0RNc2Eya0NqY3NIaWpvUnBUcHg5U2FCc0VjQ2hkaDV4bXg1eWhadEpLY1JqTEp5b0hIUUZnTjlRX2pfZDV1RXJlQml1MUhHamU5cEZMTVBlUmZpS0dTUlprU1dSNjk5TVhETnhpU0F5cm4xZC16Y09wY05Qb2xxSWVKeUxBQW9FVDVOWkRIand5SXRZbjFvVjlTbGpNSFJ1R19aUE9mLWJ3MlB4TkNBSUFTYWRsMk11UVNKYjVjTndVSHZELUk1VnJxbG13bWxueWlMVjdnQU9vT2VKOHlhaUF3aGdjN09jd2I3ME9vMC03YzNQekxEWVY0MUFROW5TMFB4N1BQa01zWVN2RzRGYW1yT2xpRkhqOVZMUFd6UjVRRHhqaUItOFM0RnZCVmo1TUw3UEhBOXYyWG9rN1MyMmpmNHlWQTM5NDNDemM2ck01WTN1VHQxY0s4TG9MNWdBcTA2LW1vdEJCak1IQ2c0WWIzZG9QZVBKZzFhSGhzaVctaGd2cUhKcWxTczVlem5Ma3kwQVA1eVhSRmVwR3F4M3VwWkpDMnBWdHlkaGIweVBvNlBiV285ajBVQkVudGRfb1k4OXVlRWxFZmgxb1E5Nmk4SXVzVmJIaVY5Wm56Rm5CYUhG)
        PROJECT_DIR: ios-test2
      cocoapods: default
    scripts:
      - echo "Using App Store API key $APP_STORE_CONNECT_KEY_IDENTIFIER"
      - keychain initialize
      # - app-store-connect fetch-signing-files "io.codemagic.banaan" --type IOS_APP_DEVELOPMENT --create
      - app-store-connect fetch-signing-files "io.codemagic.banaan" --type IOS_APP_STORE --create
      - keychain add-certificates
      - xcode-project use-profiles
      - name: Set build version
        script: |
          agvtool new-marketing-version "2.0.$BUILD_NUMBER"
          agvtool new-version -all "2.0.$BUILD_NUMBER.$PROJECT_BUILD_NUMBER"
        working_directory: $PROJECT_DIR
      - name: Build ipa
        script: |
          xcode-project build-ipa --project "$PROJECT_DIR/banaan.xcodeproj" --scheme "banaan" --archive-flags="-destination 'generic/platform=iOS'"
          mv build/ios/ipa/banaan.ipa "build/ios/ipa/banaan_2_0_${BUILD_NUMBER}_${PROJECT_BUILD_NUMBER}.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/xcarchive/**/*.app
      - build/ios/xcarchive/**/*.dSYM
      - build/ios/xcarchive/**/*.xcarchive
      - /tmp/xcodebuild_logs/*.log

  build-and-upload:
    name: Build and upload app
    inputs:
      xcode: *xcode-input
    environment:
      groups:
        - Apple API key (Admin)
      vars:
        # APP_STORE_CONNECT_ALTOOL_VERBOSE_LOGGING: true
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmZUbFhQU0JaTnhrRXR3QkJWSXVSdXFvV1I4TTFZeXdwaEFJNjhDdkVSakNwRWJHT09UeUpITUlpdFpFVHFWU29XaG9iT3poeGU2NmI4WElPVGIyVjFycWZ4cWMweXRoelZybFVyQlhNN05yOWlOT0JOTkpxZGRaM25QLWtWbnRtYlAzQ2IxSEVrQnFteVNtMHBTUl9FV0g5dFY2M01nYVJ1TXU5ajM2S0lBTEpqck1fWG9QNVRHalRULWxxOFVsV1ItR1RzbTdWMGt3UVNKMXBoT05rakRMWkMwSW5KR2ZNS3liOGxJQXVwU0luUV85UElwczhfM3N5ZE5BYXJQSnRWb0lhaUtfV1NtU2U0SWZoNlZDTE0yWEhUQWh0S0RlM3QtdGhnd2ozX09WRUxIYW0tS2dLeFE0bDJEZTJNSExubU5vb1MxUFRLUXlNb0tnNzQyNXk4TzIydENqUFJpMFB3a2dCYkFFaVlIa2ZDdHo2Y0M5QXJwYTFkSXctLVRSWVJaM1hnbVpVRTFSLTVJN3U1eXE4cWNtNFBlSkpoTlNvTk96dF9aZTFFWWt0TmZvUURDTURneDFWWDVxcmVjY3oyR1NIY2UwcWhBTVR5QnNkQTJNVXZ3Q25qNDJidXM4T2dfbFZnRjVLQTYxSW9CRm9DS1BTbGNfdzJyWHJYMFNBcEFsbmdkdUFqbWtCTFVGZzVPQjRkMlJrS0JfN0pVM3RlVmlDTU1CaTM3VS1hQ1ppVUNpZEdxZmF5SE9EbEo3bWRNVFBONzJzbDRBYzR1U0o2dWlfQjl2Zm5KNmgyOVJ1N25IV19GSC1ub0dwTEVzZml6U3JGNVY1N3MyTGZMZ2pzWW9vbzRsRGUwX3dXWkZsM1JlODlXR3l6c0FZV05pcTl2S1NCRzlYMVg1NnpxLW8xbm5Kenh1a0w4NmoyY3o1MllXaUVKT0UzV2xOVEZLUEc2QkI0aENIZnY3UFRoRGV1bU5NM0k0TFVsMVVoQzdMeUVENjdfRmc4cGJaam5heEJwUkNzdGRWY012UGNPTm5DQm9FZ3VkX0VNc3puWVh5Y1BTajRfeUkwLTRTRWVjaGg3eDI2SWxhNVRUekNMRk1HQmk2RW5WY2hEVFZ0ZGZDNXljUEZSb3NQYUpObG54dHc1RXhNTzh3bEl3UkZYWkNoT0hTa2RWeEdEWnFQTWV0dk5OX2lhTFZaSTJ3MjMxR1A2WDlMeDMyTXZBZ0hoSkgzaUVjbDVXeEhrcE9QMm4tZm9hTzI1YTJjN29Bb21iNWlKamVjQ3JPeFBGTlJQajNQWk83aXdsZ3VCY2hTZDRzenA0azQ0UFlmRkhlb0tSU013cFMyZE1OLTdpWm1qU2s3eUFEVnVTTWJoaFBTSVpkc2FhTHpIclpidUtVOWExZE9adXZVSnRtemN2RnJJS1VMU2F5NVA0Z205U3FteGFmSHdRWTBiV25XamllZTY4RHctVjVhQ2stZ1B1aEo4V1FVTDZnTk90N3RjM1kwWHJrbEhWTWFfeURrNEhiXzZNQnhQTTZhMm5ZWng2WFEzVzNvRUlReVllYkU0MWdyMTNkam10LXREVmg0aXJsNnF1UjlfUkhNOF9vY2MzRzBEQ3F5RFdlU1Vua1VNTDh4VmRXWmdUdDAwTlhBYWVycXhQdXpEWk5fV29QX0kyOFV2dnpoRm0zM1BuZEJQMlRtZVhWX3d1VHJqVzlia1FFRS1ONjF0MlZaRDN5T0haX3JNVzZIckptNzlsUjRkVjZjRFhxTzRFRnBHcWxlNkN1cUJJcC0tMVNwVnpESWVkbmU2c3RQUWpqR2Y1V01YRVBGNW1zb2VZOVc5YUpEbU1UQ0x6dmFVUVNzNlBnTjhQekFPM2JLQ29aeGRuLWRzNUp0YmRUbjdiYVRSRERfWEpnaVkxM1FILXhlN3l3UnFiSjVOaFNoajcyaGNOdER5OWtwaXk0Q184YXZBbWphQmNpeFFsZ0tiYklUVGRDMWViT0dDQXE2RDhtZ1RCMTZZcUdKNDN3Mmt6U3p3TFlzRVJ4cFh4Y1poTFRmTTU3YjNCczQyOVFXc0FUa0N1bUo1VE9XSEh0ZEw5UUVTZUN2T0Y2YktIM3NuRDRPN3d1SnVPZkJlYUg3UFZrU1haM1hZeVdfU0Y5b2tmOUhOZzN2bWlCMWNoTXJkQTFZMGg5b2laNV9Ca01EV2pLRUhpc2tHSWNYa0lnbHBfb0xMM2N1azl2bmI2NlBXeVUzLW53SEhvWnFyOG1pd3lmSzU2cXh5aDF2YVNIZTFNNjhZeDRIT1Q2VDJVem5uS0lJOUd4MEVRUnFOTnNlM2NjR3lXMWZoVXBjZWtLU0owdWMyOWZ2Mm5wUzlBVWRrSUIydUhBMVdUWVBxcTdrSDVxWHhLRFFudmswb3BlZS01S3pqRm1BUmtlX0JjTjdNVzJxNGJVV0RNc2Eya0NqY3NIaWpvUnBUcHg5U2FCc0VjQ2hkaDV4bXg1eWhadEpLY1JqTEp5b0hIUUZnTjlRX2pfZDV1RXJlQml1MUhHamU5cEZMTVBlUmZpS0dTUlprU1dSNjk5TVhETnhpU0F5cm4xZC16Y09wY05Qb2xxSWVKeUxBQW9FVDVOWkRIand5SXRZbjFvVjlTbGpNSFJ1R19aUE9mLWJ3MlB4TkNBSUFTYWRsMk11UVNKYjVjTndVSHZELUk1VnJxbG13bWxueWlMVjdnQU9vT2VKOHlhaUF3aGdjN09jd2I3ME9vMC03YzNQekxEWVY0MUFROW5TMFB4N1BQa01zWVN2RzRGYW1yT2xpRkhqOVZMUFd6UjVRRHhqaUItOFM0RnZCVmo1TUw3UEhBOXYyWG9rN1MyMmpmNHlWQTM5NDNDemM2ck01WTN1VHQxY0s4TG9MNWdBcTA2LW1vdEJCak1IQ2c0WWIzZG9QZVBKZzFhSGhzaVctaGd2cUhKcWxTczVlem5Ma3kwQVA1eVhSRmVwR3F4M3VwWkpDMnBWdHlkaGIweVBvNlBiV285ajBVQkVudGRfb1k4OXVlRWxFZmgxb1E5Nmk4SXVzVmJIaVY5Wm56Rm5CYUhG)
        PROJECT_DIR: ios-test2
      cocoapods: default
      xcode: "${{ inputs.xcode }}"
    scripts:
      - echo "Using App Store API key $APP_STORE_CONNECT_KEY_IDENTIFIER"
      - keychain initialize
      - app-store-connect fetch-signing-files "io.codemagic.banaan" --type IOS_APP_STORE --create
      - keychain add-certificates
      - xcode-project use-profiles
      - name: Set build version
        script: |
          agvtool new-marketing-version "2.0.$BUILD_NUMBER"
          agvtool new-version -all "2.0.$BUILD_NUMBER.$PROJECT_BUILD_NUMBER"
        working_directory: $PROJECT_DIR
      - name: Build ipa
        script: |
          xcode-project build-ipa --project "$PROJECT_DIR/banaan.xcodeproj" --scheme "banaan"
          mv build/ios/ipa/banaan.ipa "build/ios/ipa/banaan_2_0_${BUILD_NUMBER}_${PROJECT_BUILD_NUMBER}.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        submit_to_testflight: false
        submit_to_app_store: false
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  build-and-publish-app:
    name: Build and publish app
    inputs:
      xcode: *xcode-input
    environment:
      groups:
        - Apple API key (Admin)
      vars:
        APP_STORE_CONNECT_ALTOOL_VERBOSE_LOGGING: true
        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmZUbFhQU0JaTnhrRXR3QkJWSXVSdXFvV1I4TTFZeXdwaEFJNjhDdkVSakNwRWJHT09UeUpITUlpdFpFVHFWU29XaG9iT3poeGU2NmI4WElPVGIyVjFycWZ4cWMweXRoelZybFVyQlhNN05yOWlOT0JOTkpxZGRaM25QLWtWbnRtYlAzQ2IxSEVrQnFteVNtMHBTUl9FV0g5dFY2M01nYVJ1TXU5ajM2S0lBTEpqck1fWG9QNVRHalRULWxxOFVsV1ItR1RzbTdWMGt3UVNKMXBoT05rakRMWkMwSW5KR2ZNS3liOGxJQXVwU0luUV85UElwczhfM3N5ZE5BYXJQSnRWb0lhaUtfV1NtU2U0SWZoNlZDTE0yWEhUQWh0S0RlM3QtdGhnd2ozX09WRUxIYW0tS2dLeFE0bDJEZTJNSExubU5vb1MxUFRLUXlNb0tnNzQyNXk4TzIydENqUFJpMFB3a2dCYkFFaVlIa2ZDdHo2Y0M5QXJwYTFkSXctLVRSWVJaM1hnbVpVRTFSLTVJN3U1eXE4cWNtNFBlSkpoTlNvTk96dF9aZTFFWWt0TmZvUURDTURneDFWWDVxcmVjY3oyR1NIY2UwcWhBTVR5QnNkQTJNVXZ3Q25qNDJidXM4T2dfbFZnRjVLQTYxSW9CRm9DS1BTbGNfdzJyWHJYMFNBcEFsbmdkdUFqbWtCTFVGZzVPQjRkMlJrS0JfN0pVM3RlVmlDTU1CaTM3VS1hQ1ppVUNpZEdxZmF5SE9EbEo3bWRNVFBONzJzbDRBYzR1U0o2dWlfQjl2Zm5KNmgyOVJ1N25IV19GSC1ub0dwTEVzZml6U3JGNVY1N3MyTGZMZ2pzWW9vbzRsRGUwX3dXWkZsM1JlODlXR3l6c0FZV05pcTl2S1NCRzlYMVg1NnpxLW8xbm5Kenh1a0w4NmoyY3o1MllXaUVKT0UzV2xOVEZLUEc2QkI0aENIZnY3UFRoRGV1bU5NM0k0TFVsMVVoQzdMeUVENjdfRmc4cGJaam5heEJwUkNzdGRWY012UGNPTm5DQm9FZ3VkX0VNc3puWVh5Y1BTajRfeUkwLTRTRWVjaGg3eDI2SWxhNVRUekNMRk1HQmk2RW5WY2hEVFZ0ZGZDNXljUEZSb3NQYUpObG54dHc1RXhNTzh3bEl3UkZYWkNoT0hTa2RWeEdEWnFQTWV0dk5OX2lhTFZaSTJ3MjMxR1A2WDlMeDMyTXZBZ0hoSkgzaUVjbDVXeEhrcE9QMm4tZm9hTzI1YTJjN29Bb21iNWlKamVjQ3JPeFBGTlJQajNQWk83aXdsZ3VCY2hTZDRzenA0azQ0UFlmRkhlb0tSU013cFMyZE1OLTdpWm1qU2s3eUFEVnVTTWJoaFBTSVpkc2FhTHpIclpidUtVOWExZE9adXZVSnRtemN2RnJJS1VMU2F5NVA0Z205U3FteGFmSHdRWTBiV25XamllZTY4RHctVjVhQ2stZ1B1aEo4V1FVTDZnTk90N3RjM1kwWHJrbEhWTWFfeURrNEhiXzZNQnhQTTZhMm5ZWng2WFEzVzNvRUlReVllYkU0MWdyMTNkam10LXREVmg0aXJsNnF1UjlfUkhNOF9vY2MzRzBEQ3F5RFdlU1Vua1VNTDh4VmRXWmdUdDAwTlhBYWVycXhQdXpEWk5fV29QX0kyOFV2dnpoRm0zM1BuZEJQMlRtZVhWX3d1VHJqVzlia1FFRS1ONjF0MlZaRDN5T0haX3JNVzZIckptNzlsUjRkVjZjRFhxTzRFRnBHcWxlNkN1cUJJcC0tMVNwVnpESWVkbmU2c3RQUWpqR2Y1V01YRVBGNW1zb2VZOVc5YUpEbU1UQ0x6dmFVUVNzNlBnTjhQekFPM2JLQ29aeGRuLWRzNUp0YmRUbjdiYVRSRERfWEpnaVkxM1FILXhlN3l3UnFiSjVOaFNoajcyaGNOdER5OWtwaXk0Q184YXZBbWphQmNpeFFsZ0tiYklUVGRDMWViT0dDQXE2RDhtZ1RCMTZZcUdKNDN3Mmt6U3p3TFlzRVJ4cFh4Y1poTFRmTTU3YjNCczQyOVFXc0FUa0N1bUo1VE9XSEh0ZEw5UUVTZUN2T0Y2YktIM3NuRDRPN3d1SnVPZkJlYUg3UFZrU1haM1hZeVdfU0Y5b2tmOUhOZzN2bWlCMWNoTXJkQTFZMGg5b2laNV9Ca01EV2pLRUhpc2tHSWNYa0lnbHBfb0xMM2N1azl2bmI2NlBXeVUzLW53SEhvWnFyOG1pd3lmSzU2cXh5aDF2YVNIZTFNNjhZeDRIT1Q2VDJVem5uS0lJOUd4MEVRUnFOTnNlM2NjR3lXMWZoVXBjZWtLU0owdWMyOWZ2Mm5wUzlBVWRrSUIydUhBMVdUWVBxcTdrSDVxWHhLRFFudmswb3BlZS01S3pqRm1BUmtlX0JjTjdNVzJxNGJVV0RNc2Eya0NqY3NIaWpvUnBUcHg5U2FCc0VjQ2hkaDV4bXg1eWhadEpLY1JqTEp5b0hIUUZnTjlRX2pfZDV1RXJlQml1MUhHamU5cEZMTVBlUmZpS0dTUlprU1dSNjk5TVhETnhpU0F5cm4xZC16Y09wY05Qb2xxSWVKeUxBQW9FVDVOWkRIand5SXRZbjFvVjlTbGpNSFJ1R19aUE9mLWJ3MlB4TkNBSUFTYWRsMk11UVNKYjVjTndVSHZELUk1VnJxbG13bWxueWlMVjdnQU9vT2VKOHlhaUF3aGdjN09jd2I3ME9vMC03YzNQekxEWVY0MUFROW5TMFB4N1BQa01zWVN2RzRGYW1yT2xpRkhqOVZMUFd6UjVRRHhqaUItOFM0RnZCVmo1TUw3UEhBOXYyWG9rN1MyMmpmNHlWQTM5NDNDemM2ck01WTN1VHQxY0s4TG9MNWdBcTA2LW1vdEJCak1IQ2c0WWIzZG9QZVBKZzFhSGhzaVctaGd2cUhKcWxTczVlem5Ma3kwQVA1eVhSRmVwR3F4M3VwWkpDMnBWdHlkaGIweVBvNlBiV285ajBVQkVudGRfb1k4OXVlRWxFZmgxb1E5Nmk4SXVzVmJIaVY5Wm56Rm5CYUhG)
        PROJECT_DIR: ios-test2
      cocoapods: default
      xcode: "${{ inputs.xcode }}"
    scripts:
      - echo "Using App Store API key $APP_STORE_CONNECT_KEY_IDENTIFIER"
      - keychain initialize
      - app-store-connect fetch-signing-files "io.codemagic.banaan" --type IOS_APP_STORE --create
      - keychain add-certificates
      - xcode-project use-profiles
      - name: Set build version
        script: |
          agvtool new-marketing-version "2.0.$BUILD_NUMBER"
          agvtool new-version -all "2.0.$BUILD_NUMBER.$PROJECT_BUILD_NUMBER"
        working_directory: $PROJECT_DIR
      - name: Build ipa
        script: |
          xcode-project build-ipa --project "$PROJECT_DIR/banaan.xcodeproj" --scheme "banaan"
          mv build/ios/ipa/banaan.ipa "build/ios/ipa/banaan_2_0_${BUILD_NUMBER}_${PROJECT_BUILD_NUMBER}.ipa"
      - name: Generate notes
        script: |
          cat > release_notes.json << EOF
          [
            {"language": "en-GB", "text": "en-GB notes for build 2.0.${BUILD_NUMBER:?}.${PROJECT_BUILD_NUMBER:?}"},
            {"language": "en-US", "text": "en-US notes for build 2.0.${BUILD_NUMBER:?}.${PROJECT_BUILD_NUMBER:?}"},
            {"language": "fi", "text": "fi notes for build 2.0.${BUILD_NUMBER:?}.${PROJECT_BUILD_NUMBER:?}"}
          ]
          EOF
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: true
        beta_groups:
          - Aaa
          - Priit's group
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

  test-app:
    name: Test App
    max_build_duration: 10
    inputs:
      xcode: *xcode-input
    environment:
      xcode: "${{ inputs.xcode }}"
      cocoapods: default
    scripts:
      - name: Run tests
        script: xcode-project run-tests --project "ios-test2/banaan.xcodeproj" --scheme "banaan"
        test_report: build/ios/test/*.xml
    artifacts:
      - /tmp/xcodebuild_logs/*.log
