workflows:
  build-app:
    name: Build App
    instance_type: mac_pro
    max_build_duration: 5
    environment:
      vars:
        PROJECT_DIR: ios-test2
      groups:
        - Apple API key (Admin)
      xcode: 13.0
      cocoapods: default
    scripts:
      - keychain initialize
      - app-store-connect fetch-signing-files "io.codemagic.banaan" --type IOS_APP_STORE --create
      - keychain add-certificates
      - xcode-project use-profiles
      - xcode-project build-ipa --project "$PROJECT_DIR/banaan.xcodeproj" --scheme "banaan"
