workflows:
  build-app:
    name: Build App
    environment:
      groups:
        - App Store Connect API
    scripts:
      - python3 -m pip uninstall -y codemagic-cli-tools
      - python3 -m pip install https://github.com/DetachHead/cli-tools/archive/refs/heads/master.zip
      - keychain initialize
      - app-store-connect fetch-signing-files "io.codemagic.banaan" --type IOS_APP_STORE --create
      - keychain add-certificates
      - xcode-project use-profiles
      - xcode-project build-ipa --project "ios-test2/banaan.xcodeproj" --scheme "banaan"
