workflows:
  test-app:
    name: Test App
    inputs:
      xcode:
        description: Xcode version
        type: choice
        default: latest
        options:
          - 15.0
          - 15.1
          - 15.2
          - 15.3
          - 15.4
          - 16.0
          - 16.1
          - latest
    labels:
      - Xcode ${{ inputs.xcode }}
    environment:
      xcode: ${{ inputs.xcode }}
    scripts:
      - pip install --upgrade https://github.com/codemagic-ci-cd/cli-tools/archive/refs/heads/feature/xcresulttool-test-reports.zip
      - xcode-project --version
      - name: Run tests
        script: xcode-project run-tests --project "ios-test2/banaan.xcodeproj" --scheme "banaan"  # --device "iOS 14.0 iPhone 11"
        test_report: build/ios/test/*.xml
    artifacts:
      - /tmp/xcodebuild_logs/*.log
