workflows:
  test-app:
    name: Test App
    inputs:
      xcode:
        description: Xcode version
        type: choice
        default: 15.4
        options:
          - 15.3
          - 15.4
          - 16.0
    labels:
      - Xcode ${{ inputs.xcode }}
    environment:
      xcode: ${{ inputs.xcode }}
    scripts:
      - pip install -i https://test.pypi.org/simple/ --upgrade codemagic-cli-tools
      - xcode-project --version
      - name: Run tests
        script: xcode-project run-tests --project "ios-test2/banaan.xcodeproj" --scheme "banaan"  # --device "iOS 14.0 iPhone 11"
        test_report: build/ios/test/*.xml
    artifacts:
      - /tmp/xcodebuild_logs/*.log
