workflows:
  signing-files:
    instance_type: mac_pro
    max_build_duration: 5
    environment:
      xcode: 13.0
      ios_signing:
        certificates:
          - certificate: cert
            environment_variable: CERT_VAR
        provisioning_profiles:
          - profile: profile uploaded
            environment_variable: PROFILE_VAR
      android_signing:
        - keystore: keystore uploaded
          keystore_environment_variable: KEYSTORE_VAR
          keystore_password_environment_variable: KEYSTORE_PASS_VAR
          key_alias_environment_variable: KEYSTORE_ALIAS_VAR
    scripts:
      - printenv | grep KEY
      - sleep 30
  team-signing-files:
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: io.codemagic.banaan
    scripts:
      - xcode-project use-profiles
      - xcode-project build-ipa --project "ios-test2/banaan.xcodeproj" --scheme "banaan"
