workflows:
  build-ipa:
    name: Build ipa
    environment:
      groups:
        - Apple API key (Admin)
        - apple-code-signing
      vars:
        PROJECT_DIR: ios-test2
      # xcode: latest
      cocoapods: default
    scripts:
      - keychain initialize
      - app-store-connect fetch-signing-files "io.codemagic.banaan" --create
      - keychain add-certificates
      - xcode-project use-profiles --code-signing-setup-verbose-logging
      - name: Set build version
        script: |
          agvtool new-marketing-version "1.0.$BUILD_NUMBER"
          agvtool new-version -all "1.0.$BUILD_NUMBER.$PROJECT_BUILD_NUMBER"
        working_directory: $PROJECT_DIR
      - name: Build ipa
        script: |
          xcode-project build-ipa --project "$PROJECT_DIR/banaan.xcodeproj" --scheme "banaan" --archive-flags="-destination 'generic/platform=iOS'"
          mv build/ios/ipa/banaan.ipa "build/ios/ipa/banaan_1_0_${BUILD_NUMBER}_${PROJECT_BUILD_NUMBER}.ipa"
      - name: Generate notes
        script: |
         echo '[{"language": "en-GB", "text": "en-GB notes"}, {"language": "en-US", "text": "en-US notes"}, {"language": "fi", "text": "fi notes"}]' > release_notes.json
    artifacts:
      - build/ios/xcarchive/*.xcarchive
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

  build-app:
    name: Build app
    environment:
      vars:
        PROJECT_DIR: ios-test2
    scripts:
      - name: Set build version
        script: |
          agvtool new-marketing-version "1.0.$BUILD_NUMBER"
          agvtool new-version -all "1.0.$BUILD_NUMBER.$PROJECT_BUILD_NUMBER"
        working_directory: $PROJECT_DIR
      - name: Build app
        script: |
          xcodebuild \
            -project banaan.xcodeproj \
            -scheme banaan \
            -destination 'generic/platform=iphonesimulator' \
            -derivedDataPath ../derivedData \
            clean build
        working_directory: $PROJECT_DIR
      - name: Rename artifact
        script: mv "derivedData/Build/Products/Debug-iphonesimulator/banaan.app" "derivedData/Build/Products/Debug-iphonesimulator/banaan_1_0_${BUILD_NUMBER}_${PROJECT_BUILD_NUMBER}.app"
    artifacts:
      - derivedData/Build/Products/*-iphonesimulator/*.app

  empty:
    environment:
      xcode: 15.2
    scripts:
      - echo "Empty"

  test-app:
    name: Test App   
    inputs:
      xcode:
        description: Xcode version
        type: choice
        default: latest
        options:
          - latest
          - 16.1
          - 16.0
          - 15.4
          - 15.3
          - 15.2
          - 15.1
          - 15.0
    environment:
      xcode: ${{ inputs.xcode }}
    scripts:
      - name: Run tests
        script: xcode-project run-tests --project "ios-test2/banaan.xcodeproj" --scheme "banaan"  # --device "iOS 14.0 iPhone 11"
        test_report: build/ios/test/*.xml
    artifacts:
      - /tmp/xcodebuild_logs/*.log
